---
abstract: 'Number 2 word conversion in RUS.'
author:
  - 'Vladislav A. Safronov <vlad at yandex.ru>'
build_requires:
  Test::More: 0
  Test::More::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-RUS-Number
requires:
  Perl6::Export::Attrs: 0
  encoding: 0
  perl: v5.10.1
  strict: 0
  vars: 0
  warnings: 0
version: 0.0708
